### ISSUE TITLE
Incompatible to newer Django version

### ISSUE THREAD

**Issue by greenbigfrog** [upTee/upTee#94]
Today I tried to install upTee. A change in django breaks with your example settings files.

```
manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/[user]/uptee/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/[user]/uptee/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/[user]/uptee/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/[user]/uptee/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/[user]/uptee/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/[user]/uptee/local/lib/python2.7/site-packages/admin_tools/__init__.py", line 59, in <module>
    check_configuration()
  File "/home/[user]/uptee/local/lib/python2.7/site-packages/admin_tools/__init__.py", line 53, in check_configuration
    'loader to your %s settings variable' % loaders_var_name
django.core.exceptions.ImproperlyConfigured: You must add the "admin_tools.template_loaders.Loader" template loader to your TEMPLATE_LOADERS settings variable
```

This did also get confirmed by other people.

**Comment by SushiTee** [comment]
as I don't have the time to fix all the issues with newer django versions right now just force you device to install the django version shown in the requirements.txt

**Comment by green-big-frog** [comment]
ok.

Thanks for responding!

**Comment by green-big-frog** [comment]
Setting everything onto the version specified in the requirements.txt opened another error. I was able to fix it easliy. "just" a missing dependency #95 
Now it's working so far, but I haven't had time to finish setting it up.

**Comment by jxsl13** [comment]
The setup of this environment is sadly too complicated.

**Comment by SushiTee** [comment]
For now I changed the requirements.txt so that it won't install Django >= 1.8.
About the configuration: There is an example configuration for a production server in the docs. It should just work like this.
